### ISSUE TITLE
Ground sensor support

### ISSUE THREAD

**Issue by allsey87** [yorkrobotlab/pi-puck-e-puck1#2]
The current I2C map does not include the ground sensors from the e-puck. Perhaps this can be added to the firmware?

**Comment by RussellJoyce** [comment]
The Raspberry Pi should be the only I2C master on the bus, so the e-puck PIC can't directly access the ground sensors while a Pi-puck board is attached.

The sensors should be accessible from the Pi though (see https://pi-puck.readthedocs.io/en/latest/hardware/overview/), which I think @alanmillard has had working before using https://github.com/yorkrobotlab/pi-puck/blob/master/examples/ground-sensor/ground-sensor-test.py (we unfortunately don't have any ground sensor boards at York so I can't test this).

**Comment by allsey87** [comment]
I think I found it, I'll create a driver for it and add it to the image I am working on over at [allsey87/meta-pipuck](https://github.com/allsey87/meta-pipuck)
```
root@raspberrypi0-wifi:~# i2cdetect -y 12 0x60 0x60
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                                                 
10:                                                 
20:                                                 
30:                                                 
40:                                                 
50:                                                 
60: 60                                              
70:                                                 
```
